### ISSUE TITLE
Decide on Github workflow

### ISSUE THREAD

**Issue by agconti** [agconti/catagotchi#15]
Hey Guys -- Let's decide on a work flow for GitHub.

Because our team is distributed and will work varied asynchronous work streams I think [GItHub flow](https://github.com/agconti/cookiecutter-django-rest/issues?utf8=%E2%9C%93&q=+label%3Arelease+) will work for us the best. What do ya'll think?

**Comment by mmichaud93** [comment]
Can you explain more about GitHub flow? The link is a little unhelpful.

**Comment by agconti** [comment]
Hey @mmichaud93, 

Sorry man! that was the wrong link. Here's the right one: https://guides.github.com/introduction/flow/. Its an interactive explanation of GitHub flow made by GitHub itself.
