### ISSUE TITLE
Game Name

### ISSUE THREAD

**Issue by sebasribas** [agconti/catagotchi#26]
Brainstorm ideas for what we can call the game we are trying to make.

**Comment by mmichaud93** [comment]
I like Cat Cafe as the name of the game. It rolls off the tongue nicely and it sums up what the game is about

**Comment by mmichaud93** [comment]
We've agreed to call the team FiveFootEighty and the final game Cat Cafe. While the team name right now will not be changed, the name of the final game can be changed up until preproduction.
