### ISSUE TITLE
Update Project to Unity 5.4

### ISSUE THREAD

**Issue by mmichaud93** [agconti/catagotchi#29]
The project must be updated to support the newest version of Unity, 5.4. This includes removing the SteamVR plugin because open VR is now native to Unity.

**Comment by mmichaud93** [comment]
https://github.com/agconti/catagotchi/pull/30

**Comment by agconti** [comment]
@mmichaud93 I read the release notes; thanks for linking them. It's awesome this is now handled by Unity.
